services:
  database:
    image: postgres:13.3
    restart: on-failure
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "horse_ate_green_guinea_pig"
    volumes:
      - web4_db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "db", "-U", "admin"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "5454:5432"
    networks:
      - database_net

  backend_auth:
    build: 
      context: ./backend
      dockerfile: authService/Dockerfile
    container_name: backendAuthService
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - maven-cache:/root/.m2
    environment:
      DB_URL: postgresql://database:5432/db
      DB_USER: admin
      DB_PASSWORD: horse_ate_green_guinea_pig
      JWT_SECRET: mySuperSecretKey12345
      JWT_EXPIRATION_MS: 86_400_000
      HISTORY_SERVICE_HOST: "backendHistoryService"
      HISTORY_SERVICE_PORT: 9090
      JWT_ISSUER: AuthService
    ports:
      - "5001:8080"
    networks:
      - database_net
      - web_server_net

  backend_geometry:
    build: 
      context: ./backend
      dockerfile: geometryService/Dockerfile
    container_name: backendGeometryService
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - maven-cache:/root/.m2
    environment:
      DB_URL: postgresql://database:5432/db
      DB_USER: admin
      DB_PASSWORD: horse_ate_green_guinea_pig
      JWT_SECRET: mySuperSecretKey12345
      JWT_EXPIRATION_MS: 86_400_000
      JWT_ISSUER: AuthService
    ports:
      - "5002:8080"
    networks:
      - database_net
      - web_server_net

  backend_history:
    build: 
      context: ./backend
      dockerfile: historyService/Dockerfile
    container_name: backendHistoryService
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - maven-cache:/root/.m2
    environment:
      DB_URL: postgresql://database:5432/db
      DB_USER: admin
      DB_PASSWORD: horse_ate_green_guinea_pig
      JWT_SECRET: mySuperSecretKey12345
      JWT_EXPIRATION_MS: 86_400_000
      JWT_ISSUER: AuthService
    ports:
      - "5003:8080"
    networks:
      - database_net
      - web_server_net

  frontend:
    build: ./frontend
    container_name: frontend
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web_server_net

volumes:
  web4_db_data:
  maven-cache:

networks:
  database_net:
    driver: bridge
  web_server_net:
    driver: bridge
